stages:
  - prepare
  - test

services:
  - mysql
  - ansi/mosquitto

variables:
  MYSQL_ROOT_PASSWORD: "password"
  MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

connect:
  stage: prepare
  image: mysql
  script:
  - mysql --user=root --password="$MYSQL_ROOT_PASSWORD" --host=mysql < "resources/NodeMCUTest.sql"
  
dev:
  stage: test
image: kaiwinter/docker-java8-maven
maven: 
    script: 
        - mvn install -B 
        - cat target/site/jacoco/index.html