stages:
  - prepare
  - test

services:
  - mysql

variables:
  MYSQL_ROOT_PASSWORD: "password"
  MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

connect:
  stage: prepare
  image: mysql
  script:
  - mysql --user=root --host=mysql < "resources/NodeMCUTest.sql"
  
dev:
  stage: test
image: kaiwinter/docker-java8-maven
maven: 
    script: 
        - apt-get update && apt-get install mosquitto
        - mosquitto
        - mvn install -B 
        - cat target/site/jacoco/index.html